import type { Metadata } from "next";
import "./globals.css";
import { geistSans, geistMono } from "@/fonts/font";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className="bg-space-1 h-screen w-screen bg-fixed overflow-auto text-space-4 flex"
		>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
